
package views;

import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class ViewMascotas extends javax.swing.JPanel {
    public String imagePath = null;
    
    /**
     * Creates new form ViewMascotas
     */
    public ViewMascotas() {
        initComponents();
        
        ImageIcon wallpaper = new ImageIcon("src/assets/no-image.png");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_DEFAULT));
        lblImage.setIcon(icono);
    }
    
    public ImageIcon resizeImage(String imagePath, byte[] pic) {
        ImageIcon myImage = null;
        if(imagePath != null) {
            myImage = new ImageIcon(imagePath);
        } else {
            myImage = new ImageIcon(pic);
        }
        
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img2);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarMascota = new javax.swing.JButton();
        btnBuscarMascota = new javax.swing.JButton();
        btnEditarMascota = new javax.swing.JButton();
        btnAgregarMascota = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMascotas = new javax.swing.JTable();
        lblImage = new javax.swing.JLabel();
        btnAgregarImagen = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoMascota = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRaza = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbxEstadoMascota = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtFechaNac = new com.toedter.calendar.JDateChooser();
        txtNombreMascota = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        btnEliminarMascota.setBackground(new java.awt.Color(84, 56, 220));
        btnEliminarMascota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminarMascota.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarMascota.setText("Eliminar");
        btnEliminarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMascotaActionPerformed(evt);
            }
        });
        add(btnEliminarMascota);
        btnEliminarMascota.setBounds(560, 470, 170, 31);

        btnBuscarMascota.setBackground(new java.awt.Color(84, 56, 220));
        btnBuscarMascota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscarMascota.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarMascota.setText("Buscar");
        btnBuscarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMascotaActionPerformed(evt);
            }
        });
        add(btnBuscarMascota);
        btnBuscarMascota.setBounds(380, 470, 170, 31);

        btnEditarMascota.setBackground(new java.awt.Color(84, 56, 220));
        btnEditarMascota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditarMascota.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarMascota.setText("Editar");
        btnEditarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMascotaActionPerformed(evt);
            }
        });
        add(btnEditarMascota);
        btnEditarMascota.setBounds(200, 470, 170, 31);

        btnAgregarMascota.setBackground(new java.awt.Color(84, 56, 220));
        btnAgregarMascota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregarMascota.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarMascota.setText("Agregar");
        btnAgregarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMascotaActionPerformed(evt);
            }
        });
        add(btnAgregarMascota);
        btnAgregarMascota.setBounds(20, 470, 170, 31);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        tblMascotas.setAutoCreateRowSorter(true);
        tblMascotas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOMBRE", "RAZA", "ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMascotas.setGridColor(new java.awt.Color(255, 255, 255));
        tblMascotas.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jScrollPane1.setViewportView(tblMascotas);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 270, 710, 180);

        lblImage.setBackground(new java.awt.Color(204, 204, 255));
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/no-image.png"))); // NOI18N
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 3));
        add(lblImage);
        lblImage.setBounds(500, 10, 230, 200);

        btnAgregarImagen.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarImagen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/upload.png"))); // NOI18N
        btnAgregarImagen.setText("Subir foto");
        btnAgregarImagen.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnAgregarImagen.setPreferredSize(new java.awt.Dimension(120, 40));
        btnAgregarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarImagenActionPerformed(evt);
            }
        });
        add(btnAgregarImagen);
        btnAgregarImagen.setBounds(500, 220, 230, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(84, 56, 220));
        jLabel7.setText("Código");
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 20));
        add(jLabel7);
        jLabel7.setBounds(20, 10, 120, 20);

        txtCodigoMascota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigoMascota.setPreferredSize(new java.awt.Dimension(220, 20));
        txtCodigoMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoMascotaActionPerformed(evt);
            }
        });
        add(txtCodigoMascota);
        txtCodigoMascota.setBounds(140, 10, 220, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(84, 56, 220));
        jLabel9.setText("Raza");
        jLabel9.setPreferredSize(new java.awt.Dimension(120, 20));
        add(jLabel9);
        jLabel9.setBounds(20, 90, 120, 20);

        txtRaza.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRaza.setPreferredSize(new java.awt.Dimension(220, 20));
        txtRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazaActionPerformed(evt);
            }
        });
        add(txtRaza);
        txtRaza.setBounds(140, 90, 220, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(84, 56, 220));
        jLabel10.setText("Peso");
        jLabel10.setPreferredSize(new java.awt.Dimension(120, 20));
        add(jLabel10);
        jLabel10.setBounds(20, 130, 120, 20);

        txtPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPeso.setPreferredSize(new java.awt.Dimension(220, 20));
        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });
        add(txtPeso);
        txtPeso.setBounds(140, 130, 220, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(84, 56, 220));
        jLabel13.setText("Fecha de nacimiento");
        jLabel13.setPreferredSize(new java.awt.Dimension(120, 20));
        add(jLabel13);
        jLabel13.setBounds(20, 220, 180, 20);

        cbxEstadoMascota.setBackground(new java.awt.Color(84, 56, 220));
        cbxEstadoMascota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxEstadoMascota.setForeground(new java.awt.Color(255, 255, 255));
        cbxEstadoMascota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo", "Disponible", "Adoptado" }));
        cbxEstadoMascota.setPreferredSize(new java.awt.Dimension(120, 20));
        cbxEstadoMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoMascotaActionPerformed(evt);
            }
        });
        add(cbxEstadoMascota);
        cbxEstadoMascota.setBounds(210, 170, 150, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(84, 56, 220));
        jLabel14.setText("Estado");
        jLabel14.setPreferredSize(new java.awt.Dimension(120, 20));
        add(jLabel14);
        jLabel14.setBounds(20, 170, 180, 20);
        add(txtFechaNac);
        txtFechaNac.setBounds(210, 220, 150, 30);

        txtNombreMascota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreMascota.setPreferredSize(new java.awt.Dimension(220, 20));
        txtNombreMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMascotaActionPerformed(evt);
            }
        });
        add(txtNombreMascota);
        txtNombreMascota.setBounds(140, 50, 220, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(84, 56, 220));
        jLabel8.setText("Nombres");
        jLabel8.setPreferredSize(new java.awt.Dimension(120, 20));
        add(jLabel8);
        jLabel8.setBounds(20, 50, 120, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMascotaActionPerformed

    private void btnBuscarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMascotaActionPerformed

    private void btnEditarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMascotaActionPerformed

    private void btnAgregarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMascotaActionPerformed

    private void btnAgregarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarImagenActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.image", "jpg", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lblImage.setIcon(resizeImage(path, null));
            imagePath = path;
        } else {
            System.out.println("Archivo no seleccionado");
        }
    }//GEN-LAST:event_btnAgregarImagenActionPerformed

    private void txtCodigoMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoMascotaActionPerformed

    private void txtRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazaActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void cbxEstadoMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadoMascotaActionPerformed

    private void txtNombreMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMascotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarImagen;
    public javax.swing.JButton btnAgregarMascota;
    public javax.swing.JButton btnBuscarMascota;
    public javax.swing.JButton btnEditarMascota;
    public javax.swing.JButton btnEliminarMascota;
    public javax.swing.JComboBox<String> cbxEstadoMascota;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblImage;
    public javax.swing.JTable tblMascotas;
    public javax.swing.JTextField txtCodigoMascota;
    public com.toedter.calendar.JDateChooser txtFechaNac;
    public javax.swing.JTextField txtNombreMascota;
    public javax.swing.JTextField txtPeso;
    public javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables
}
