
package views;

import java.awt.Color;
import javax.swing.JPanel;

public class Catalogo extends javax.swing.JPanel {

    /**
     * Creates new form Catalogo
     */
    public Catalogo() {
        initComponents();
        
        resetColor(item1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        item1 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        item1.setBackground(new java.awt.Color(153, 153, 255));
        item1.setMinimumSize(new java.awt.Dimension(250, 220));
        item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                item1MouseClicked(evt);
            }
        });
        item1.setLayout(null);

        nombre.setBackground(new java.awt.Color(51, 51, 51));
        nombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("Nombre");
        item1.add(nombre);
        nombre.setBounds(50, 220, 186, 20);

        lblImage.setBackground(new java.awt.Color(204, 204, 255));
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/no-image.png"))); // NOI18N
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204), 3));
        item1.add(lblImage);
        lblImage.setBounds(20, 10, 230, 200);
        lblImage.getAccessibleContext().setAccessibleParent(this);

        add(item1);
        item1.setBounds(240, 70, 270, 270);

        btnBack.setBackground(new java.awt.Color(84, 56, 220));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Atrás");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(30, 470, 120, 31);

        btnNext.setBackground(new java.awt.Color(84, 56, 220));
        btnNext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Siguiente");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        add(btnNext);
        btnNext.setBounds(160, 470, 120, 31);

        btnSelect.setBackground(new java.awt.Color(84, 56, 220));
        btnSelect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSelect.setForeground(new java.awt.Color(255, 255, 255));
        btnSelect.setText("Seleccionar");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        add(btnSelect);
        btnSelect.setBounds(559, 470, 170, 31);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectActionPerformed

    private void item1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MouseClicked
        // TODO add your handling code here:
        setColor(item1);
    }//GEN-LAST:event_item1MouseClicked

    void setColor(JPanel panel) {
        panel.setBackground(new Color(255,86,201));
    }
    
    void resetColor(JPanel panel) {
        panel.setBackground(new Color(84,56,220));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnNext;
    public javax.swing.JButton btnSelect;
    private javax.swing.JPanel item1;
    public javax.swing.JLabel lblImage;
    public javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
